development:
  adapter: postgresql
  database: db/development
  username: scratchoff
  host: localhost
  encoding: UTF8

test:
  adapter: postgresql
  database: db/test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/production
  pool: 5
  timeout: 5000
