development:
  adapter: postgresql
  database: db/development
  username: zach
  password:
  host: localhost
  encoding: unicode
  pool: 5

test:
  adapter: postgresql
  database: db/test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/production
  pool: 5
  timeout: 5000
